### ISSUE TITLE
bug: can still access the Login page even though already logged in 

### ISSUE THREAD

**Issue by htnghia1423** [hardingadonis/ligevan#308]
**Describe the bug**
Can still access the Login page for Admin even though already logged in.

**To Reproduce**

1. Go to [Login page for admin](http://localhost:5173/admin/login)
2. Fill user name and password, then click button `Đăng nhập`
3. On the Dashboard page (if loggin successfully), access the [Login page for admin](http://localhost:5173/admin/login) again

**Expected behavior**
Can not access the Login page when Login successfully. Try to redirect Login page to Dashboard if there is token in local storage.

**Screenshots**
![image](https://github.com/user-attachments/assets/304b6f9f-f8f1-4f8a-be76-c6b341e12935)

**Environments**

- Browser [Microsoft Edge]
- Version [130.0.2849.56]

**Additional context**
N/A

**Comment by punhe** [comment]
Hi @htnghia1423 , 
This bug is already fix, when access to login but have the token, website will be access to dashboard.
Please check this again.
Best Regards,
punhe

**Comment by htnghia1423** [comment]
Done
