### ISSUE TITLE
bug: format (admin)

### ISSUE THREAD

**Issue by yuhtnguyen** [hardingadonis/ligevan#316]
**Describe the bug**
- Go to Admin page
- Click view center/ course/ voucher

actual:  Center, left, right style for fields that are not matching (kiểm tra cột STT/ Cột 'giá' của course nên căn giữa )
expected: Center, left, right style for fields that are matching

**Comment by htnghia1423** [comment]
**Error:** Content in column `STT` are not centered at Center and Course list page. And style align of column `Giá` at Course page will keep align right at current. Dev will update style align.

**Note:** @yuhtnguyen Please remember to add full screenshots for actual and expected results to the next error log. With the above description it is sometimes difficult for us to visualize the actual things and the results you expect. Thanks and best regards.

**Comment by yuhtnguyen** [comment]
bug fixed
