### ISSUE TITLE
bug: create new center (/admin/centers/create)

### ISSUE THREAD

**Issue by yuhtnguyen** [hardingadonis/ligevan#317]
1. go to Admin Page
2. Go to center 
3. Click: create new center

actual: hiển thị message lỗi khi nhập tên cho trung tâm
![image](https://github.com/user-attachments/assets/bf84d04e-b9cc-4184-b1c4-973c383d7d2f)

expected: không hiển thị message lỗi

**Comment by htnghia1423** [comment]
Hi @yuhtnguyen,

This issue have been fixed. Please help me to check it.

Best regards,
NghiaHT

**Comment by yuhtnguyen** [comment]
The error has been successfully fixed.
