### ISSUE TITLE
bug: create new center (/admin/centers/create)

### ISSUE THREAD

**Issue by yuhtnguyen** [hardingadonis/ligevan#318]
1. go to Admin Page
2. Go to center
3. Click: create new center

actual: Không hiển thị bất kỳ message lỗi nào ở các field nhưng lại 'không thể tạo trung tâm' 
(gợi ý: em nghĩ nó bị lỗi ở chỗ số điện thoại: có thể là sđt đã tồn tại hoặc sđt ko đúng số điện thoại của việt nam)
![image](https://github.com/user-attachments/assets/4e5ea08f-f672-420b-8608-13c5ac6fb0b6)

expected: 
* Hiển thị messgae cho người dùng biết đang gặp lỗi gì không thể tạo trung tâm 
( hoặc ==> tạo trung tâm thành công)

**Comment by htnghia1423** [comment]
**Error:** This issue is because email and phone number are unique for each centers. So message "Can't create center" is that the center that you crate have been existed. 

Dev will check this issue and update message to validate existing center.

**Comment by yuhtnguyen** [comment]
bug fixed
