### ISSUE TITLE
bug: create new course (/admin/centers/course)

### ISSUE THREAD

**Issue by yuhtnguyen** [hardingadonis/ligevan#319]
1. go to Admin Page
2. Go to course
3. Click: create new course
actual: Không hiển thị bất kỳ message lỗi ở field 'giá' khi empty
![Uploading 01.png…]()

expected: Hiển thị message lỗi thì field 'giá' empty

**Comment by htnghia1423** [comment]
Hi @yuhtnguyen,

I have checked and message error have displayed when field `Giá khoá học` is empty. But it have another error is Not matching UI of error message as other field in form. Please follow issue #320 for this additional error.

Best regards,
NghiaHT

**Comment by yuhtnguyen** [comment]
1. go to Admin Page
2. Go to course
3. Click: create new course
3. Click on the 'course price' field -> click out
4. actual: The 'course price' field automatically accepts a value of 0 VND -> clicking the 'create course' button does not display an error message.
I think this is a bug, please check and fix it.

@htnghia1423

**Comment by punhe** [comment]
Hi @yuhtnguyen, 
I think if admin want to create free course, the number 0 have to accepted. 
Please check this again
Thanks,
punhe

**Comment by yuhtnguyen** [comment]
okok
