### ISSUE TITLE
bug: create new voucher (/admin/centers/voucher)

### ISSUE THREAD

**Issue by yuhtnguyen** [hardingadonis/ligevan#320]
1. go to Admin Page
2. Go to voucher
3. lick: create new voucher

actual: UI message lỗi, không matching với UI message lỗi khi tạo trung tâm với tạo khóa học
![image](https://github.com/user-attachments/assets/b5272c38-df8e-4d95-b02d-edea3bb2a712)
![image](https://github.com/user-attachments/assets/0494186a-1b0f-4d9c-b474-e7a991052074)
![image](https://github.com/user-attachments/assets/f03a98f4-8ad4-468b-8a2f-af08d0c7abc5)

expected: matching với UI message lỗi khi tạo trung tâm với tạo khóa học

**Comment by htnghia1423** [comment]
**Error:** Not matching UI message error in validate field input. Will remove bolder at message error and keep content of message as current.

**Comment by yuhtnguyen** [comment]
@htnghia1423 I tested again, the error is still not fixed, or am I making a mistake here?
Please check again for me?

![01](https://github.com/user-attachments/assets/69e08afb-3690-4c02-a887-ddf612ee6fd9)
![02](https://github.com/user-attachments/assets/5fc90bc7-4cae-49b8-af63-e01d8f717cc8)

**Comment by htnghia1423** [comment]
Hi @yuhtnguyen,

This issue has not been fixed yet, and it's still being assigned to dev so you don't need to retest this issue yet.

Best regards,
NghiaHT

**Comment by yuhtnguyen** [comment]
bug fixed
