### ISSUE TITLE
bug: create new voucher (/admin/centers/voucher)

### ISSUE THREAD

**Issue by yuhtnguyen** [hardingadonis/ligevan#323]
1. go to Admin Page
2. Go to voucher
3. Click: create new voucher

actual: Hiển thị lỗi "Thời gian bắt đầu phải ở sau thời điểm hiện tại!" khi input vào hợp lệ
![image](https://github.com/user-attachments/assets/1b2eb994-5813-4204-a368-c93b17fd790f)

expected: ko hiển thị message lỗi

**Comment by htnghia1423** [comment]
Hi @yuhtnguyen,

This issues will refer as issue #327. Please help me to check it.

Best regards,
NghiaHT

**Comment by yuhtnguyen** [comment]
fixed
