### ISSUE TITLE
bug: update course (/admin/courses/edit/6717a88f13c11b554d98d8b4)

### ISSUE THREAD

**Issue by yuhtnguyen** [hardingadonis/ligevan#326]
1. Go to admin page
2. Go to course
3. Go to center detail
4. Click update course

actual: 
ko update được giá tiền cho course 
![image](https://github.com/user-attachments/assets/da8b68bb-c421-4b7d-9a53-0dbc19fa566b)

expected: update giá tiền thành công

**Comment by htnghia1423** [comment]
Hi @yuhtnguyen,

This issue has been fixed. Please help me to check it.

Best regards,
NghiaHT

**Comment by yuhtnguyen** [comment]
Fixed
