### ISSUE TITLE
bug: create teacher for center (layout)

### ISSUE THREAD

**Issue by yuhtnguyen** [hardingadonis/ligevan#358]
**Describe the bug**
Vị trí: http://localhost:5174/admin/centers/671899496b1aa85ebed122c5/teachers/create

**To Reproduce**

1. Go to admin
2. Click on center
3. Click on center detail
4. Click on teacher detail
5. Click 'create new teacher'

actual: UI đang bị lệch sang phải do avt trống 
![01](https://github.com/user-attachments/assets/d97f0ea4-5c4f-4e01-91d5-325dd5864220)

expected: gợi ý nên đề hình avt mặc định trước, khi người dùng cập nhật url avt của họ thì đọc file ảnh từ url

**Comment by htnghia1423** [comment]
Hi @yuhtnguyen,

This issue has been fixed. Please help me to check it again.

Best regards,
NghiaHT

**Comment by yuhtnguyen** [comment]
BUG FIXED
