### ISSUE TITLE
Đối với student, những course không có class vẫn hiển thị, gây khó khăn trong việc chọn lựa lớp đăng ký

### ISSUE THREAD

**Issue by linhlm0210** [hardingadonis/ligevan#369]
**Step:**
1. Login với role = student
2. Ở dashboard chọn center ở dropdown
3. Chọn 1 course bất kỳ
4. Vào course detail không có class nào

**Evidence:**
![image](https://github.com/user-attachments/assets/65fe7ceb-7ceb-44df-a55d-aa3fbcf37e69)

**Expect:** Chỉ hiển thị những course đã có class, việc hiển thị như hiện tại gây khó khăn cho việc tìm các course đã mở lớp học, tốn thời gian

**Comment by htnghia1423** [comment]
Sẽ update data, mỗi course sẽ có 1 class
