### ISSUE TITLE
bug: check attendance of teacher 

### ISSUE THREAD

**Issue by yuhtnguyen** [hardingadonis/ligevan#378]
**Describe the bug**
Vị trí: http://localhost:5173/teacher/schedule

1. Go to teacher
2. Click on schedule
3. Filter từ 03-09/11/2024 
4. Select 'attendance' for any slot

actual: 
Status: 'đã dạy' vẫn có thể click 'điểm danh'
Expected:  Status: 'đã dạy' ko thể click 'điểm danh'
![01](https://github.com/user-attachments/assets/dd404179-e187-4565-882f-609a6b3bbe5a)

**Comment by bakaqc** [comment]
completed
