### ISSUE TITLE
Tạo mới hoàn toàn teacher, nhưng sau đó tạo class thì không có teacher vừa tạo trong list value

### ISSUE THREAD

**Issue by linhlm0210** [hardingadonis/ligevan#379]
**Step:** 
1. Login với role = admin
2. Vào center detail
3. Tạo mới teacher 
4. Tạo mới class
5. Teacher vừa mới tạo không có trong list value

**Evidence:**
<img width="958" alt="image" src="https://github.com/user-attachments/assets/fe9b7fb5-0433-4de8-a758-f12a80244c52">
<img width="959" alt="image" src="https://github.com/user-attachments/assets/0e98282d-c9ea-4230-887d-2919d767e4f8">

**Comment by bakaqc** [comment]
completed
