### ISSUE TITLE
bug: dropdown center ở tính lương cho teacher

### ISSUE THREAD

**Issue by linhlm0210** [hardingadonis/ligevan#380]
Không hiển thị hết danh sách tất cả center, hiển thị như vậy không biết teacher ở center nào, và giáo viên có điều kiện như thế nào mới được hiển thị ở table này?
- Chỉ cần là teacher 
- Hay đã nhận lớp mới hiện
<img width="959" alt="image" src="https://github.com/user-attachments/assets/6b316626-992c-4b74-b3d2-04490924fa4c">

**Comment by bakaqc** [comment]
completed
