### ISSUE TITLE
bug: business của assign class cho teacher

### ISSUE THREAD

**Issue by linhlm0210** [hardingadonis/ligevan#381]
Mỗi teacher chỉ được nhận dạy 1 lớp, vậy sau khi lớp học đó kết thúc (đã dạy xong), thì trong api vẫn trả về là teacher đó vẫn có class đã từng dạy, làm cách nào để assign cho họ 1 class mới khi đã hoàn thành xong việc dạy class cũ.

**Comment by htnghia1423** [comment]
Tính năng sẽ update trong tương lại.
